language: node_js
node_js: 
    - "11.1.0"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn && yarn global add codecov
script: 
    - yarn test
 
    

